services:
  mc:
    container_name: mc
    image: itzg/minecraft-server
    tty: true
    stdin_open: true
    networks:
      - frontend
    environment:
      EULA: "TRUE"
    volumes:
      - ./data:/data

networks:
  frontend:
    external: true