upstream backends {
    server filaco-dev:3000;
    server 95.81.119.208:3000;
    server 109.69.57.238:3000;
}

server {
    listen 3001;

    location / {
        proxy_pass http://backends;
    }
}
