services:
  ollama:
    container_name: ollama
    image: ollama/ollama:rocm
    restart: unless-stopped
    networks:
      - frontend
    group_add:
      - 985 # video
      - 989 # render
    devices:
      - /dev/kfd:/dev/kfd
      - /dev/dri:/dev/dri
    volumes:
      - "$OLLAMA_HOME:/root/.ollama"
    environment:
      HSA_OVERRIDE_GFX_VERSION: 11.0.2
      # AMD_LOG_LEVEL: 3
      # OLLAMA_DEBUG: 1
      OLLAMA_CONTEXT_LENGTH: 64000
      # OLLAMA_KEEP_ALIVE: -1
      OLLAMA_MAX_LOADED_MODELS: 1

  # TODO: remove it when desktop app is ready
  openwebui:
    container_name: openwebui
    image: ghcr.io/open-webui/open-webui:main
    restart: unless-stopped
    networks:
      - frontend
    volumes:
      - "$OPENWEBUI_HOME:/app/backend/data"

networks:
  frontend:
    external: true
